[phases.setup]
aptPkgs = ["ffmpeg", "python3.11", "python3.11-venv", "python3.11-dev"]

[phases.install]
cmds = [
  "python3.11 -m venv /tmp/venv",
  ". /tmp/venv/bin/activate",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [". /tmp/venv/bin/activate"]

[variables]
PYTHON_VERSION = "3.11.9"
NIXPACKS_PYTHON_VERSION = "3.11.9"

