[phases.setup]
aptPkgs = ["ffmpeg"]
cmds = ["mise use --yes python@3.11.9"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[variables]
PYTHON_VERSION = "3.11.9"
NIXPACKS_PYTHON_VERSION = "3.11.9"

